config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {:registrations => "users/registrations"}

  root 'welcome#index'
  resources :leaves do
    patch :cancel, on: :member
  end
  
  resources :reviews

  namespace :admin do
    resources :circulars do
      patch :update_published, on: :member
    end
    resources :dashboard, only: [:index]
    resources :holidays
    resources :employees do 
      get "generate_csv", on: :collection
    end  
    resources :leaves do
      patch :cancel, on: :member
    end
    
    get 'reviews/employees' => 'reviews#employees_list', as: :employee_list
    get 'employees/:employee_id/reviews' => 'reviews#index', as: :employee_review_list
    get 'employees/:employee_id/reviews/:id' => 'reviews#show', as: :review

  end 

end

app/controllers/admin/employees_controller.rb
class Admin::EmployeesController < Admin::AuthenticationController
  
  def index
    if params[:search].present?
      term = params[:search]
      @employees = User.where.not(role: 'admin').where('email LIKE ? or employee_id =? or first_name LIKE ?', "%#{term}%", term.to_i, "%#{term}%").paginate(:page => params[:page], :per_page => 5)
    else
      @employees = User.all_employees.order('employee_id ASC').paginate(:page => params[:page], :per_page => 10)
    end
  end

  def new
    @employee = User.new
  end

  def create
    @employee = User.all_employees.new(user_params)
    if @employee.save
      @employee.add_leave_balance
      redirect_to admin_employees_path
    else
      render 'new'
    end
  end

  def edit
    @employee = User.all_employees.find(params[:id])
  end

  def update
    @employee = User.find(params[:id])
    if @employee.update_attributes(user_params)
      redirect_to  admin_employees_path
    else
      render 'edit'
    end
  end

  def show
    @employee = User.find(params[:id])
  end

  def destroy
    @employee = User.all_employees.find(params[:id]) 
    @employee.update(deleted: true)
    @employee.leaves.update_all(deleted: true)
    redirect_to admin_employees_path
  end

  def generate_csv
    @employees = User.includes(:balances).where.not(role: "admin").order('employee_id ASC')
    respond_to do |format|
      format.html { send_data @employees.to_csv(params[:month]), filename: "Team Members Leave Report - #{Time.zone.now.strftime('%d/%m/%Y, %I:%M %p')}.csv" }
    end
  end 

  private
    def user_params
     params.require(:user).permit(:first_name, :last_name, :mobile,:role ,:email,:password,:manager_id, :joining_date, :image)
    end
    
end

app/helpers/admin/employees_helper.rb
module Admin::EmployeesHelper
end

app/views/admin/employees/_form.html.erb
<% if action_name.eql?("edit") %>
  <div class="row">
    <div class="col-md-6">
      <% if @employee.image.present? %>
        <%= image_tag(@employee.image_url.to_s, class: 'img-circular') %><br />
      <% else %>
        <%= image_tag 'user_image.png', class: 'img-circular' %><br />
      <% end %>
    </div>
    <div class="col-md-6">
      <%= f.input :image, label: false %>
    </div>
  </div>
<% else %>
  <div class="img-padding">
    <%= f.input :image, label: false %>
  </div>
<% end %>
<br />
<div class="col-md-6 form-group has-feedback">
  <%= f.input :first_name, class: 'form-control has-feedback-right', placeholder: 'First Name', label: false %>
  <span class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
</div>
<div class="col-md-6 form-group has-feedback">
  <%= f.input :last_name, class: 'form-control has-feedback-right', placeholder: 'Last Name', label: false %>
  <span class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
</div>
<div class="col-md-6 form-group has-feedback">
  <%= f.input :email, class: 'form-control has-feedback-right', placeholder: 'Email', label: false %>
  <span class="fa fa-envelope form-control-feedback right" aria-hidden="true"></span>
</div>
<% if f.object.new_record? %>
  <div class="col-md-6 form-group has-feedback">
    <%= f.input :password, class: 'form-control has-feedback-right', placeholder: 'Password', label: false %>
    <span class="fa fa-lock form-control-feedback right" aria-hidden="true"></span>
  </div>
<% end %>
<div class="col-md-6 form-group has-feedback">
  <%= f.input :mobile, class: 'form-control has-feedback-right', placeholder: 'Mobile no', label: false %>
  <span class="fa fa-phone form-control-feedback right" aria-hidden="true"></span>
</div>
<div class="col-md-6 form-group has-feedback">
  <%= f.input :role, collection: [['Admin', 'admin'], ['Employee', 'employee'],['Manager','manager']], label: false, :prompt=>"select role" %>
</div>
<div class="col-md-6 form-group has-feedback">
  <%= f.input :manager_id,collection: assign_managers, label_method: :second, value_method: :first, label: false, :prompt=>"select manager"  %> 
</div>
<div class="col-md-6 form-group has-feedback">
  <div class="form-group email optional user_email form-group-invalid">
    <input type="text" name="user[joining_date]" id="user_joining_date" autocomplete="off" class="form-control string optional" placeholder="Joining Date" value='<%= @employee.joining_date %>'>
    <span class="fa fa-calendar form-control-feedback right" aria-hidden="true"></span>
    <% if @employee.errors.present? && @employee.errors[:joining_date].present? %>
      <div class="invalid-feedback">Joining date can't be blank</div>
    <% end %>
  </div>
</div>

app/views/admin/employees/edit.html.erb
<div class="x_title">
  <h2>Edit Employee</h2>
  <div class="clearfix"></div>
</div>
<div class="x_content">
  <%= simple_form_for(@employee,url: admin_employee_path, html: {class: 'form-horizontal form-label-left input_mask'}) do |f| %>
    <%= render partial: 'form', :locals => {:f => f} %>
    <div class="col-md-6 form-group">
    </div>
    <div class="col-md-6 form-group text-right">
      <%=f.submit "Update", class: "btn btn-primary" %>
    </div>
 <%end%>
</div>

app/views/admin/employees/index.html.erb
<div class="x_title">
  <h2>Employees</h2>
  <div class="clearfix"></div>
</div>
<div class="col-md-12">
  <div class="row">
    <div class="col-md-6">
      <div class="">
        <%= form_tag(admin_employees_path, method: 'get') do %>
          <div class="col-md-6">
            <%= text_field_tag(:search, params[:search], class: 'form-control', placeholder: 'Search Employee ID or name') %>
          </div>
          <%= submit_tag("Search", name: nil, class: 'btn btn-info') %>
        <% end %>
      </div>
    </div>
    <div class="col-md-3">
      <%= form_tag(generate_csv_admin_employees_path, method: 'get') do %>
        <div class="col-md-6">
          <%= select_tag "month", options_for_select(choose_month), class: 'form-control' %>
        </div>
        <div class="col-md-6">
          <%= submit_tag("CSV Report with Leave Balance", data: { disable_with: false } ,class: 'btn btn-info')%>
        </div>
      <% end %>
      <%#=link_to "CSV Report with Leave Balance", admin_employees_path(format: 'csv', employee_report: true),class: "btn btn-info pull-right" %>
    </div>
    <div class="col-md-3">
      <%=link_to "New Employee",new_admin_employee_path, method: 'get', class: "btn btn-info pull-right" %>
    </div>
  </div>
  
  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th>Employee ID</th>
        <th>Joining Date</th>
        <th>Leave Balance</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Mobile</th>
        <th>Role</th>
        <th>Email</th>
        <th>Manager</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @employees.each do |employee|%>
        <tr>
          <td><%= employee.employee_id %></td>
          <td><%= employee.joining_date %></td>
          <td><%= employee.leave_balance %></td>
          <td><%= employee.first_name %></td>
          <td><%= employee.last_name %></td>
          <td><%= employee.mobile %></td>
          <td><%= employee.role %></td>
          <td><%= employee.email %></td>
          <td><%= employee.manager.first_name rescue ''%></td>
          <td>
            <%= link_to admin_employee_path(employee) do %>
              <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
            <% end %> |
            <%= link_to edit_admin_employee_path(employee), method: 'get' do %>
              <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            <% end %> | 
            <%= link_to admin_employee_path(employee),data: {:confirm => 'Are you sure?'}, :method => :delete do %>
              <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
            <% end %>
           </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @employees,renderer: BootstrapPagination::Rails%>
</div>

app/views/admin/employees/new.html.erb
<div class="x_title">
  <h2>New Employee</h2>
  <div class="clearfix"></div>
</div>
<div class="x_content">
  <%= simple_form_for(@employee,url: admin_employees_path, html: {class: 'form-horizontal form-label-left input_mask'}) do |f| %>
      <%= render partial: 'form', :locals => {:f => f} %>
      <div class="col-md-6 form-group">
      </div>  
      <div class="col-md-6 form-group text-right">
        <%=f.submit "Submit", class: "btn btn-primary" %>
      </div>
  <%end%>
</div>

app/views/admin/employees/show.html.erb
<div class="x_title">
  <h2>Employee Detail</h2>
  <div class="clearfix"></div>
</div>
<div class="col-md-7">
  <div class="panel panel-default">
    <div class="panel-heading">Employee Detail</div>
    <div class="panel-body panel_font_size">
      <% if @employee.image.present? %>
        <%= image_tag(@employee.image_url.to_s, class: 'img-circular') %><br />
      <% else %>
        <%= image_tag 'user_image.png', class: 'img-circular' %><br />
      <% end %>
      <div class="row">
      <div class="col-md-4">
        <strong>Employee ID :</strong>
      </div>
      <div class="col-md-6"> 
        <%= @employee.employee_id %>    
      </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <strong> First Name :</strong>
        </div>
        <div class="col-md-6"> 
          <%= @employee.user_name %>    
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <strong> Last Name :</strong>
        </div>
        <div class="col-md-6"> 
          <%= @employee.last_name %>    
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <strong> Mobile :</strong>
        </div>
        <div class="col-md-6"> 
          <%= @employee.mobile %>    
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <strong> Role :</strong>
        </div>
        <div class="col-md-6"> 
          <%= @employee.role %>    
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <strong> Email :</strong>
        </div>
        <div class="col-md-6"> 
          <%= @employee.email %>    
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <strong> Manager :</strong>
        </div>
        <div class="col-md-6"> 
          <%= @employee.manager.first_name rescue ''%>    
        </div>
      </div>
    </div>
  </div>

</div>