config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {:registrations => "users/registrations"}

  root 'welcome#index'
  resources :leaves do
    patch :cancel, on: :member
  end
  
  resources :reviews

  namespace :admin do
    resources :circulars do
      patch :update_published, on: :member
    end
    resources :dashboard, only: [:index]
    resources :holidays
    resources :employees do 
      get "generate_csv", on: :collection
    end  
    resources :leaves do
      patch :cancel, on: :member
    end
    
    get 'reviews/employees' => 'reviews#employees_list', as: :employee_list
    get 'employees/:employee_id/reviews' => 'reviews#index', as: :employee_review_list
    get 'employees/:employee_id/reviews/:id' => 'reviews#show', as: :review

  end 

end

app/models/circular.rb
class Circular < ApplicationRecord
  validates_presence_of :note, :published_at
  validates_length_of :note, :maximum => 200

  scope :active,-> {where(published: true).map{|c| c.note}}
end

app/controllers/admin/circulars_controller.rb
class Admin::CircularsController < Admin::AuthenticationController

  before_action :set_circular, expect: [:new, :create]

  def index
    @circulars = Circular.all
  end 
  
  def create
    @circular = Circular.new(circular_params)
    if @circular.save
      flash[:notice] = "New Circular Successfully Created."
      redirect_to admin_circulars_path
    else
      render 'new'
    end
  end
  def new
    @circular = Circular.new 
  end 

  def edit;end

  def show;end

  def update
    if @circular.update_attributes(circular_params)
      redirect_to  admin_circulars_path
    else
      render 'edit'
    end
  end

  def destroy
    @circular.destroy
    redirect_to admin_circulars_path
  end 


  def update_published
    @circular.published = params[:published]
    if @circular.save
      redirect_to admin_circulars_path
    end
  end 

  private 
    def circular_params
      params.require(:circular).permit(:note, :published_at, :published)
    end

    def set_circular
      @circular = Circular.find_by_id(params[:id])
    end
end

app/views/admin/circulars/_form.html.erb
<div class="col-md-7 col-sm-6 col-xs-12 form-group has-feedback">
  <%= f.input :note, label: false, as: :text, placeholder: 'Note' %>
  <span class="fa fa-pencil form-control-feedback right" aria-hidden="true"></span>
</div>
<br>
<div class="col-md-7 col-sm-6 col-xs-12 form-group has-feedback margin_bottom_20">
  <input type="text" name="circular[published_at]"  autocomplete="off" class="form-control has-feedback-left holiday_date" placeholder='Published at' value='<%= @circular.published_at %>'>
  <% if @circular.errors.present? && @circular.errors[:published_at].present? %>
    <div class="invalid-feedback">Published date can't be blank</div>
  <% end %>
  <span class="fa fa-calendar form-control-feedback right" aria-hidden="true"></span>
</div>
<div class="col-md-7 col-sm-6 col-xs-12 form-group has-feedback">
  <%= f.check_box :published, {}, "true", "false" %>
  <label>Published</label>
</div>

app/views/admin/circulars/edit.html.erb
<div class="x_title">
  <h2>Edit circular</h2>
  <div class="clearfix"></div>
</div>
<div class="x_content">
  <%= simple_form_for(@circular,url: admin_circular_path, html: {class: 'form-horizontal form-label-left input_mask'}) do |f| %>
    <%= render partial: 'form', :locals => {:f => f} %>
    <div class="col-md-7 col-sm-6 col-xs-12 form-group has-feedback text-right">
      <%=f.submit "Update Circular", class: "btn btn-info" %>
    </div>
  <%end%>
</div>

app/views/admin/circulars/index.html.erb
<div class="x_title">
  <h2>Circulars</h2>
  <div class="clearfix"></div>
</div>
<div class="row">
  <div class="pull-right">
    <%= link_to "New Circular", new_admin_circular_path, method: :get, class: 'btn btn-info' %>
  </div>
</div>
 <table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th>Note</th>
      <th>Published at</th> 
      <th>Published</th>
      <th>Actions</th>  
    </tr>
  </thead>
  <tbody>
    <% @circulars.each do |circular|%>
      <tr>
        <td><%= truncate(circular.note, length: 100) %></td>
        <td><%= circular.published_at %></td>
        <td><%= circular.published ? 'Active' : 'Inactive' %></td>
        <td>
          <%= link_to "#{circular.published ? 'Inactive' : 'Active'}", update_published_admin_circular_path(circular, published: circular.published ? false : true), method: :patch, class: 'link-underline' %> |
          <%= link_to edit_admin_circular_path(circular), method: :get do %>
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
          <% end %> |
          <%= link_to admin_circular_path(circular), method: :get do %>
            <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
          <% end %> |  
          <%= link_to admin_circular_path(circular), method: :delete, data: {confirm: "Are you sure?"} do %>
            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
          <% end %>
        </td>            
      </tr>
    <% end %>
  </tbody>  
</table> 

app/views/admin/circulars/new.html.erb
<div class="x_title">
  <h2>New circular</h2>
  <div class="clearfix"></div>
</div>
<div class="x_content">
  <%= simple_form_for(@circular,url: admin_circulars_path, html: {class: 'form-horizontal form-label-left input_mask'}) do |f| %>
    <%= render partial: 'form', :locals => {:f => f} %>
    <div class="col-md-7 col-sm-6 col-xs-12 form-group has-feedback text-right">
      <%=f.submit "Create Circular", class: "btn btn-info" %>
    </div>
  <%end%>
</div>

app/views/admin/circulars/show.html.erb
<div class="x_title">
  <h2>Circular Detail</h2>
  <div class="clearfix"></div>
</div>
<div class="col-md-7">
  <div class="panel panel-default">
    <div class="panel-heading">Circular Detail</div>
    <div class="panel-body panel_font_size">
      <div class="row">
      <div class="col-md-4">
        <strong> Note :</strong>
      </div>
      <div class="col-md-6"> 
        <%= @circular.note %>    
      </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <strong> Published date :</strong>
        </div>
        <div class="col-md-6"> 
          <%= @circular.published_at %>    
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <strong> Status :</strong>
        </div>
        <div class="col-md-6"> 
          <%= @circular.published %>    
        </div>
      </div>
    </div>
  </div>
</div>