config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {:registrations => "users/registrations"}

  root 'welcome#index'
  resources :leaves do
    patch :cancel, on: :member
  end
  
  resources :reviews

  namespace :admin do
    resources :circulars do
      patch :update_published, on: :member
    end
    resources :dashboard, only: [:index]
    resources :holidays
    resources :employees do 
      get "generate_csv", on: :collection
    end  
    resources :leaves do
      patch :cancel, on: :member
    end
    
    get 'reviews/employees' => 'reviews#employees_list', as: :employee_list
    get 'employees/:employee_id/reviews' => 'reviews#index', as: :employee_review_list
    get 'employees/:employee_id/reviews/:id' => 'reviews#show', as: :review

  end 

end

app/models/holiday.rb
class Holiday < ApplicationRecord
  validates :date, uniqueness: true
  validates_presence_of :date, :occasion
end

app/controllers/admin/holidays_controller.rb
class Admin::HolidaysController < Admin::AuthenticationController

  def index
    @holidays = Holiday.order(:date)
  end 

  def new
    @holiday = Holiday.new
  end 
  def edit
    @holiday = Holiday.find(params[:id])
  end  

  def create
    @holiday = Holiday.new(holiday_params)
    if @holiday.save
      flash[:notice] = "New Holiday Successfully Created ."
      redirect_to admin_holidays_path    
    else
      render :new
    end    
  end

  def update
    @holiday = Holiday.find(params[:id])
    if @holiday.update_attributes(holiday_params)
      redirect_to  admin_holidays_path
    else
      render 'edit'
    end
  end
  
   def destroy
    @holiday = Holiday.find(params[:id]) 
    @holiday.destroy
    redirect_to admin_holidays_path
  end

  private 
    def holiday_params
      params.require(:holiday).permit(:date, :occasion)
    end
end

app/helpers/admin/holiday_helper.rb
module Admin::HolidayHelper
end

app/views/admin/holidays/_form.html.erb
<div class="col-md-7 col-sm-6 col-xs-12 form-group has-feedback margin_bottom_20">
  <input type="text" name="holiday[date]"  autocomplete="off" class="form-control has-feedback-left holiday_date" placeholder='Occasion date' value='<%= @holiday.date %>'>
  <% if @holiday.errors.present? && @holiday.errors[:date].present? %>
    <div class="invalid-feedback">date can't be blank</div>
  <% end %>
  <span class="fa fa-calendar form-control-feedback right" aria-hidden="true"></span>
</div>
<br>
<div class="col-md-7 col-sm-6 col-xs-12 form-group has-feedback">
  <%= f.input :occasion, label: false, as: :text, placeholder: 'Occasion' %>
  <span class="fa fa-pencil form-control-feedback right" aria-hidden="true"></span>
</div>

app/views/admin/holidays/edit.html.erb
<div class="x_title">
  <h2>Edit Holiday</h2>
  <div class="clearfix"></div>
</div>
<div class="x_content">
  <%= simple_form_for(@holiday,url: admin_holiday_path, html: {class: 'form-horizontal form-label-left input_mask'}) do |f| %>
    <%= render partial: 'form', :locals => {:f => f} %>
     <div class="col-md-7 col-sm-6 col-xs-12 form-group has-feedback text-right">
      <%=f.submit "Update", class: "btn btn-info" %>
    </div> 
  <%end%> 
</div>

 

app/views/admin/holidays/index.html.erb
<div class="x_title">
  <h2>Holidays</h2>
  <div class="clearfix"></div>
</div>
<div class="row">
  <div class="pull-right">
    <%= link_to "New Holiday", new_admin_holiday_path, method: :get, class: 'btn btn-info' %>
  </div>
</div>
 <table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th>Date</th>
      <th>Occasion</th> 
      <th>Action</th>  
    </tr>
  </thead>
  <tbody>
    <% @holidays.each do |holiday|%>
      <tr>
        <td><%= holiday.date.strftime("%d-%m-%Y") rescue'' %></td>
        <td><%= holiday.occasion %></td>
        <td><%= link_to edit_admin_holiday_path(holiday), method: :get do %>
          <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
        <% end %> | 
        <%= link_to admin_holiday_path(holiday),data: {:confirm => 'Are you sure?'}, :method => :delete do %>
          <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
        <% end %></td>                     
      </tr>
    <% end %>
  </tbody>  
</table> 

app/views/admin/holidays/new.html.erb
<div class="x_title">
  <h2> New Holidays</h2>
  <div class="clearfix"></div>
</div>
<div class="x_content">
  <%= simple_form_for(@holiday,url: admin_holidays_path, html: {class: 'form-horizontal form-label-left input_mask'}) do |f| %>
    <%= render partial: 'form', :locals => {:f => f} %>
    <div class="col-md-7 col-sm-6 col-xs-12 form-group has-feedback text-right">
      <%=f.submit "Create holiday", class: "btn btn-info" %>
    </div>
  <%end%>
</div>