config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {:registrations => "users/registrations"}

  root 'welcome#index'
  resources :leaves do
    patch :cancel, on: :member
  end
  
  resources :reviews

  namespace :admin do
    resources :circulars do
      patch :update_published, on: :member
    end
    resources :dashboard, only: [:index]
    resources :holidays
    resources :employees do 
      get "generate_csv", on: :collection
    end  
    resources :leaves do
      patch :cancel, on: :member
    end
    
    get 'reviews/employees' => 'reviews#employees_list', as: :employee_list
    get 'employees/:employee_id/reviews' => 'reviews#index', as: :employee_review_list
    get 'employees/:employee_id/reviews/:id' => 'reviews#show', as: :review

  end 

end

app/views/shared/_sidebar.html.erb
<div class="col-md-3 left_col">
  <div class="left_col scroll-view">
    <div class="navbar nav_title" style="border: 0;">
      <%= link_to root_path, class: "site_title" do %>
        <%= image_tag('logo.png', height: 40, class: 'img_class')%>
      <% end %>
      <!-- <a href="" class="site_title"><i class="fa fa-paw"></i> <span>Witmates</span></a> -->
    </div>

    <div class="clearfix"></div>

    <!-- menu profile quick info -->
    <div class="profile clearfix">
      <div class="profile_pic">
        <% if current_user.image.present? %>
          <%= image_tag( current_user.image_url.to_s, class: "img-circle profile_img", alt: "...") %>
        <% else %>
          <%= image_tag( 'user_image.png', class: "img-circle profile_img", alt: "...") %>
        <% end %>
      </div>
      <div class="profile_info">
        <span>Welcome,</span>
        <h2><%= current_user.user_name %></h2>
      </div>
    </div>
    <!-- /menu profile quick info -->

    <br />

    <!-- sidebar menu -->
    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
      <div class="menu_section">
        <ul class="nav side-menu">
          <% if current_user && current_user.admin? %>
            <li><%= link_to admin_dashboard_index_path do %>
                <i class="fa fa-home"></i>Dashboard
                <% end %>
            </li>
            <li>
              <%= link_to admin_leaves_path do %>
                <i class="fa fa-tasks" aria-hidden="true"></i> Leaves
              <% end %>
            </li>
            <li><%= link_to admin_holidays_path do %>
                <i class="fa fa-calendar"></i>Holidays
                <% end %>
            </li>
            <li><%= link_to admin_employees_path do %>
                <i class="fa fa-group"></i>Employees
               <% end %>
            </li>
             <li><%= link_to admin_circulars_path do %>
                <i class="fa fa-bell"></i>Circulars
               <% end %>
            </li>
            <li><%= link_to admin_employee_list_path do %>
              <i class="fa fa-pencil"></i>Reviews
              <% end %>
            </li>

          <% elsif current_user && current_user.employee? %>
            <li><%= link_to root_path do %>
                <i class="fa fa-home"></i>Home
                <% end %>
            </li>
            <li><%= link_to new_leave_path, method: :get do %>
                <i class="fa fa-calendar"></i>Apply Leave
                <% end %>
            </li>
             <li><%= link_to new_leave_path(:team_member =>true), method: :get do %>
                <i class="fa fa-calendar"></i>Apply Leave for TM
                <% end %>
            </li>
            <li><%= link_to leaves_path, method: :get do %>
                <i class="fa fa-eye"></i>View leaves
                <% end %>
            </li>
            <li><%= link_to reviews_path, method: :get do %>
                <i class="fa fa-eye"></i>Reviews
                <% end %>
            </li>
          <% elsif current_user && current_user.manager? %>
            <li><%= link_to root_path do %>
                <i class="fa fa-home"></i>Home
                <% end %>
            </li>
            <li><%= link_to leaves_path, method: :get do %>
                <i class="fa fa-tasks"></i>View leaves
                <% end %>
            </li>
            <li><%= link_to new_leave_path, method: :get do %>
                <i class="fa fa-calendar"></i>Apply Leave
                <% end %>
            </li>
             <li><%= link_to new_leave_path(:team_member =>true), method: :get, class: "tm-apply-leave-btn" do %>
                <i class="fa fa-calendar"></i>Apply Leave for TM
                <% end %>
            </li>
            <li><%= link_to reviews_path, method: :get do %>
                <i class="fa fa-eye"></i>Reviews
                <% end %>
            </li>
            <% end %> 
        </ul>
      </div>
    </div>
    <!-- /sidebar menu -->

    <!-- /menu footer buttons -->
    <div class="sidebar-footer hidden-small">
      <a href="/users/edit" data-toggle="tooltip" data-placement="top" title="Settings">
        <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
      </a>
    </div>
    <!-- /menu footer buttons -->
  </div>
</div>

app/views/shared/_top_navbar.html.erb
<div class="top_nav">
  <div class="nav_menu">
    <nav>
      <% if user_signed_in? %>
      <div class="nav toggle">
        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
      </div>
      <% else %>
      <%= link_to root_path do %>
        <%= image_tag('logo.png', class: 'logo-image')%>
      <% end %>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li class="">
          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <% if current_user.image.present? %>
              <%= image_tag current_user.image_url.to_s %><%= current_user.user_name %>
            <% else %>
              <%= image_tag 'user_image.png', class: '' %><%= current_user.user_name %>
            <% end %>
            <span class="fa fa-angle-down"></span>
          </a>
          <ul class="dropdown-menu dropdown-usermenu pull-right">
            <li>
              <%= link_to edit_user_registration_path do %>
                Change Password <i class="glyphicon glyphicon-cog pull-right"></i>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: 'DELETE' do %>
                Log Out <i class="fa fa-sign-out pull-right"></i>
              <% end %>
            </li>
          </ul>
        </li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
     </nav>
  </div>
</div>